version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/new_chatapp

 hooks:
  BeforeInstall: 
    - location: /Scripts/stop_server.sh
      timeout: 300
       runas: root
  AfterInstall:
    - location: /Scripts/start_server.sh
      timeout: 300
      runas: root
  
