version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/new_chatapp

 hooks:
  BeforeInstall:
    - location: Scripts/stop-server.sh
      runas: ubuntu
  AfterInstall:
    - location: Scripts/Restart.sh
      runas: ubuntu
