version: 0.0
os: linux
files:
  - source: /
    destination: /
 hooks:
  BeforeInstall:
    - location: Scripts/stop-server.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: Scripts/Restart.sh
      timeout: 100
      runas: root
