- stage: Deploy
  displayName: 'Deploy Chat-app'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: 
      name: dev
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          
          - task: 'Bash@3'
            inputs:
              targetType: 'inline'
              script: |
                # Modify deployment script based on the app type
                echo "Starting deployment script run"
                cd '/home/ubuntu/new-chatapp/fundoo/' && unzip -o $(Build.BuildId).zip -d /home/backend-instance/chatapp
                rm -rf *.zip
                source venv/bin/activate
                pip3 install -r requirements.txt
                cd '/home/ubuntu/new-chatapp/fundoo' && python3 manage.py migrate
